#!/bin/bash
# Dump (to stdout) the SQL commands to create DP tables.

set -euo pipefail

setup_dir=$(realpath $(dirname $0))

db_server=$($setup_dir/get_config_value.php db_server)
db_user=$($setup_dir/get_config_value.php db_user)
db_password=$($setup_dir/get_config_value.php db_password)
db_name=$($setup_dir/get_config_value.php db_name)
code_dir=$($setup_dir/get_config_value.php code_dir)

export LC_ALL=POSIX
# because on www.pgdp.net, none of the LC_* are defined,
# and LANG=en_US.UTF-8, which produces case-insensitivity
# in grep and sed.

# We don't want to dump schema for *all* tables in the database.
# So how will we determine which ones to dump?
if [ "${1-}" = '--table-list-from-db' ]; then
    table_list_source='db'
    # If they've passed in another arg, assume it's the DB name
    if [ -n "${2-}" ]; then
        db_name=$2
    fi
elif [ "${1-}" = '--table-list-from-code' ]; then
    table_list_source='code'
else
    table_list_source='code'
fi

get_table_names()
{
    if [ $table_list_source = db ]; then
        mysql --host $db_server --user=$db_user --password="$db_password" \
            -D $db_name \
            --skip-column-names --batch --execute='show tables' |
        grep -v \
            -e '^projectID' \
            -e '^phpbb_' \
            -e pgdptest_voter_info \
            |
        sort
    elif [ $table_list_source = code ]; then
        find $setup_dir/.. -type f \
            \( -name '*.php' -o -name '*.inc' -o -name '*.pl' \) |

        xargs grep -E '(FROM|INTO|JOIN) ' |

        # Suppress some non-SQL occurrences of those keywords and vendor & test code
        grep -v \
            -e /vendor/ \
            -e /SETUP/tests/ \
            -e /SETUP/upgrade/ \
            -e 'the FROM clause' \
        |

        sed -n -e'
            s/.*\<FROM  *//
            s/.*\<INTO  *//
            s/.*\<JOIN  *//
            s/^\([a-z_0-9][a-z_0-9]*\).*/\1/p
            s/^`\([^`]*\)`.*/\1/p
        ' |

        # Exclude temporary & MySQL internal tables.
        grep -v -x \
            -e access_log_summary \
            -e active_page_counts \
            -e genre_translations \
            -e project_event_subscriptions_grouped_by_project \
            -e information_schema \
        |

        sort -u
    else
        echo 1>&2 "bad table_list_source: '$table_list_source'"
        exit 1
    fi
}

tables=$(get_table_names)

if true; then
    # The order tables are dumped is not consistent and it's possible to have
    # tables with foreign keys before the foreign key tables are created.
    # To make sure the dump is loadable, we have to temporarily disable
    # foreign key checks for this session.
    echo "SET FOREIGN_KEY_CHECKS=0;"

    mysqldump --host $db_server --user=$db_user --password="$db_password" \
        --no-data --quote-names --add-drop-table=FALSE --force \
        $db_name $tables |

    # Remove column collation specs & auto increment as those can vary
    sed -E '
        s/AUTO_INCREMENT=[0-9]+ //
        s/COLLATE \w+\s*//
        s/ COLLATE=\w+//
    ' |

    # Ensure the per-table chunks are in a consistent order:
    php -f  $setup_dir/sort_mysqldump.php |

    # Skip MySQL command sequences as they may be version-specific
    # (and generate a lot of noise in the diffs).
    grep -v '/*!'

    # Re-enable foreign key checks
    echo "SET FOREIGN_KEY_CHECKS=1;"
fi
