#!/bin/sh

# Stop on undefined variables or errors
set -u
set -e

if [ $# != 1 ]; then
    echo 'usage: update_from_github <path-to-site-config-file>'
    exit 1
fi

this_script_file=$0
site_config_file=$1

export script_dir=`dirname $this_script_file`
export config_dir=`dirname $site_config_file`

# ------------------------------------------------------------------------------

# Overview of this script:
# ------------------------
#
# The code snapshot will be installed at
#     $CODE_DIR.new
# (i.e., that directory will contain pinc, tools, etc.)
#
# If $SHIFT_TO_LIVE (defined in the config file) is 'yes',
# or it's 'prompt' and the user answers 'y',
# then $CODE_DIR.new will be moved to $CODE_DIR.
# If that directory already exists, it will first be renamed as
#     $CODE_DIR.bak
# and if *that* directory already exists, it will be REMOVED.
#
# So if this script is being invoked periodically, any "manual"
# changes you make within the snapshot hierarchy will soon disappear.
# Basically, you should treat it as read-only (although I've
# occasionally made quick changes to test some code that I'm
# working on at home).
#
# In order to make the resulting site functional, this script
# makes a few tweaks to the snapshot, replacing certain
# patterns in certain files with site-specific strings.

# ------------------------------------------------------------------------------

check()
{
    status=$?
    blurb=$1
    if [ $status != 0 ]; then
        echo "'$blurb' returned status $status, so exiting"
        exit 1
    fi
}

# ------------------------------------------------------------------------------

# Set CODE_DIR
. $site_config_file

abort=/bin/false
if [ "$TAG" = "" ]; then
    echo "Error: config file did not define TAG."
    abort=/bin/true
fi
if [ "$CODE_DIR" = "" ]; then
    echo "Error: config file did not define CODE_DIR."
    abort=/bin/true
fi
if [ "$GROUP" = "" ]; then
    echo "Error: config file did not define GROUP."
    abort=/bin/true
fi
if [ "$SHIFT_TO_LIVE" = "" ]; then
    echo "Error: config file did not define SHIFT_TO_LIVE."
    abort=/bin/true
fi

if [ "$SITE_VARS" = "" ]; then
    echo "Error: config file did not define SITE_VARS."
    abort=/bin/true
fi

if $abort; then
    echo "Aborting due to config errors."
    exit 1
fi

# just as an early warning/reassurance...
echo "Note: SHIFT_TO_LIVE = $SHIFT_TO_LIVE"
echo


# ------------------------------------------------------------------------------
# Get snapshot of code from github.com

$script_dir/get_git_clone $TAG $GROUP $CODE_DIR.new
check "get_git_clone"

# ------------------------------------------------------------------------------
# Install site-specific info.

cp $SITE_VARS $CODE_DIR.new/pinc/site_vars.php
chgrp $GROUP $CODE_DIR.new/pinc/site_vars.php

# ------------------------------------------------------------------------------
# Install dependencies

$script_dir/install_dependencies.sh -p -d $CODE_DIR.new
chgrp -R $GROUP $CODE_DIR.new/vendor
chgrp -R $GROUP $CODE_DIR.new/node_modules

# ------------------------------------------------------------------------------
# Apply any local customizations.

if [ -e $config_dir/customize_deployment ]; then
    echo "Running local deployment customization script..."
    . $config_dir/customize_deployment
fi

# ------------------------------------------------------------------------------

echo ""
$script_dir/diff_rq $CODE_DIR $CODE_DIR.new
echo ""

echo "NOTE: using TAG = $TAG"
echo ""

if [ $SHIFT_TO_LIVE = yes ]; then
    # fine
    :

elif [ $SHIFT_TO_LIVE = no ]; then
    echo "SHIFT_TO_LIVE is 'no', so exiting without an install"
    exit 1

elif [ $SHIFT_TO_LIVE = prompt ]; then
    echo -n "Install $CODE_DIR.new? [yn] "
    read response
    echo -n "Your response was '$response', so "
    if [ "$response" != y ]; then
        echo "exiting."
        exit 1
    fi
    echo "continuing..."

else
    echo "Error: unexpected value for SHIFT_TO_LIVE: '$SHIFT_TO_LIVE'."
    echo "Assuming SHIFT_TO_LIVE='no', so exiting without an install."
    exit 1
fi

# ------------------------------------------------------------------------------

# "Install" the new hierarchy.
echo "installing the new hierarchy..."

if [ -d $CODE_DIR.bak ]; then
    rm -rf $CODE_DIR.bak
    check "rm $CODE_DIR.bak"
fi

if [ -d $CODE_DIR ]; then
    mv $CODE_DIR $CODE_DIR.bak
    check "mv $CODE_DIR $CODE_DIR.bak"
fi

mv $CODE_DIR.new $CODE_DIR
check "mv $CODE_DIR.new $CODE_DIR"

# ------------------------------------------------------------------------------
# vim: ai sw=4 ts=100
